#!/usr/bin/env bash

# Transfers a file from our client to a server:
# Accepts 4 parameters:
# 1. The file to transfer
# 2. The server to transfer to
# 3. The username to use
# 4. The password to use

# Check if the correct number of parameters were passed
if [ "$#" -ne 4 ]; 
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
